name: Export builds

on:
  pull_request: {}
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build-mac:
    name: Make Mac build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.4.12f1
          targetPlatform: StandaloneOSX
          
      - name: Set permissions
        run: |
          chmod a+x build/StandaloneOSX.app/Contents/MacOS/*
          chmod a+x build/StandaloneOSX.app
          
      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: openware-mac
          path: build
